src/fheroes2/spell/spell_info.h: add missing '#include <cstdint>'
Without the change build fails on weekly `gcc-13` snapshot as:

    ../fheroes2/spell/spell_info.h:33:5: error: 'uint32_t' does not name a type
       33 |     uint32_t getSpellDamage( const Spell & spell, const uint32_t spellPower, const HeroBase * hero );
          |     ^~~~~~~~
    ../fheroes2/spell/spell_info.h:25:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
       24 | #include <string>
      +++ |+#include <cstdint>