src/fheroes2/game/game_over.h: add missing '#include <cstdint>'
Without the change build fails on `gcc-13` as:

    ../fheroes2/game/game_over.h:35:23: error: found ':' in nested-name-specifier, expected '::'
       35 |     enum conditions_t : uint32_t
          |                       ^