src/fheroes2/kingdom/color.h: add missing '#include <cstdint>'
Without the change build fails on `gcc-13` as:

    ../fheroes2/kingdom/color.h:51:10: error: expected identifier before ':' token
       51 |     enum : uint8_t
          |          ^